<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="common.fs" />
    <Compile Include="react-native.fs" />
    <Compile Include="expo.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="*.fsproj; *.fs" PackagePath="fable\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.7.*" />
    <PackageReference Include="Fable.Elmish" Version="5.0.2" />
    <PackageReference Include="Fable.React" Version="9.*" />
  </ItemGroup>
</Project>
