name: .NET

on:
  push:
    branches: [ v5.x ]
  pull_request:
    branches: [ v5.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: ./build.fsx
